### ISSUE TITLE
jeo主题下不兼容，tepass支付插件带的登录界面无法使用

### ISSUE THREAD

**Issue by podipod** [KawaiiZapic/Typecho-reCAPTCHA-v3#1]
在jeo主题下不兼容，tepass支付插件带的登录界面也无法调用，jeo主题下无法显示点击按钮，tepass登录界面无法调用不显示。

**Comment by KawaiiZapic** [comment]
你说的是这个么: https://github.com/HaoOuBa/Joe  
Joe主体存在[表单提交不完全](https://github.com/HaoOuBa/Joe/blob/master/assets/js/joe.global.js#L315)的情况, 请联系作者获得帮助
  
tepass为付费插件, 我无法得知内部运作原理, 因此也不能提供帮助.    
根据收集到的信息, tepass登陆界面貌似独立于Typecho的登陆界面, 因此插件无法提供保护.

**Comment by podipod** [comment]
> 你说的是这个么: https://github.com/HaoOuBa/Joe  
> Joe主体存在[表单提交不完全](https://github.com/HaoOuBa/Joe/blob/master/assets/js/joe.global.js#L315)的情况, 请联系作者获得帮助
>   
> tepass为付费插件, 我无法得知内部运作原理, 因此也不能提供帮助.    
> 根据收集到的信息, tepass登陆界面貌似独立于Typecho的登陆界面, 因此插件无法提供保护.  

tepass已经集成了，谢谢你
