### ISSUE TITLE
[功能请求] Secret Key 用 Password 而非 Text 存储

### ISSUE THREAD

**Issue by cherinyy** [KawaiiZapic/Typecho-reCAPTCHA-v3#3]
我本来想自己改，但是不知道怎么改🤣

主要是因为浏览器会自动记录表单内容，这样密钥就被浏览器记录了。
如果能加上 `autocomplete="off"` 那也行。

改成 Password 并添加 `autocomplete="new-password"` 可以阻止其填写网站密码，但无法阻止其询问是否保存密码。

**Comment by KawaiiZapic** [comment]
type=hidden的表单项不应该会被浏览器存储

**Comment by cherinyy** [comment]
> type=hidden的表单项不应该会被浏览器存储

但似乎并没有这个参数？
![image](https://user-images.githubusercontent.com/9050713/145341985-7e85361e-3d19-49b1-a882-d67bac1baa3e.png)

**Comment by KawaiiZapic** [comment]
> > type=hidden的表单项不应该会被浏览器存储
> 
> 但似乎并没有这个参数？ ![image](https://user-images.githubusercontent.com/9050713/145341985-7e85361e-3d19-49b1-a882-d67bac1baa3e.png)

这个代码由typecho生成, 插件无法控制

**Comment by cherinyy** [comment]
> > > type=hidden的表单项不应该会被浏览器存储
> > 
> > 
> > 但似乎并没有这个参数？ ![image](https://user-images.githubusercontent.com/9050713/145341985-7e85361e-3d19-49b1-a882-d67bac1baa3e.png)
> 
> 这个代码由typecho生成, 插件无法控制

我知道，但插件没有用 `Hidden`，而是用的 `Text`
https://github.com/KawaiiZapic/Typecho-reCAPTCHA-v3/blob/f6661822a05f8b88400623d7b401bda8d4c6b589/Plugin.php#L32

噢，你是说实际执行的时候不会被浏览器存储，但我是说在后台插件配置页面时，会被浏览器自动填充存储内容。

**Comment by KawaiiZapic** [comment]
https://github.com/KawaiiZapic/Typecho-reCAPTCHA-v3/tree/feat-prevent_save_secret

未做测试, 直接下载本分支替换原插件即可

**Comment by cherinyy** [comment]
> https://github.com/KawaiiZapic/Typecho-reCAPTCHA-v3/tree/feat-prevent_save_secret
> 
> 未做测试, 直接下载本分支替换原插件即可

正常使用，在主分支加上这两行就行了，非常感谢
https://github.com/KawaiiZapic/Typecho-reCAPTCHA-v3/blob/ee6dc0da1898b973523aefea54bc37721fc3b9f7/Plugin.php#L38-L39
